name: Execute AWS Lambda Function

on:
  schedule:
    - cron: '0 6,18 * * *'
  workflow_dispatch:  # Permite la ejecución manual

jobs:
  ejecutar_lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke Lambda Function
        uses: gagoar/invoke-aws-lambda@master
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1' 
          functionName: 'access_to_web' 
          payload: '{ "url": "https://big-five-prediction.3.us-1.fl0.io/" }'
      - name: Store response payload to file
        run: echo '${{ fromJSON(steps.foobar.outputs.response).Payload }}' # Solo mostrar por pantalla
        #run: echo '${{ fromJSON(steps.foobar.outputs.response).Payload }}' > invocation-response.json # Generar un archivo
